// ----------------------------------------------------------------------------
// etfImplementationCommentText
// ----------------------------------------------------------------------------
// Pure (React-free) resolver for the text shown in the Build tab's ETF
// Implementation table "Comment" column. Two consumers must stay in sync:
//
//   1. EtfImplementationCommentCell — the on-screen table cell renderer.
//   2. exportEtfImplementationXlsx — the Excel export.
//
// Both must show the same string for the same ETF. Resolution rules
// (Task #207):
//
//   • commentSource === "manual" or undefined-with-text → the stored
//     `comment` / `commentDe` text is operator-curated; render verbatim.
//   • commentSource === "justetf" → stored prose was scraped from
//     justETF's "Investment objective" panel; render verbatim.
//   • commentSource === "auto" → stored prose was generated by the
//     deterministic describeEtf() template against an older snapshot of
//     the look-through profile. We recompute describeEtf() at render
//     time and prefer the live result whenever it produces non-empty
//     text — so a refreshed look-through (geo / sector / topHoldings
//     change) is reflected immediately, without waiting for the monthly
//     `lookthrough-refresh` backfill to re-stamp the row.
//   • Empty comment + no source tag → no stored prose at all; fall
//     through to the live describeEtf() template.
//
// In every "auto / fallback" branch the cell applies italic styling so
// the runtime-fallback branch stays visually distinguishable from
// curated text. The resolver returns `source: "auto"` for both the
// stale-override case and the empty-row fallback so the cell doesn't
// have to know the difference.
// ----------------------------------------------------------------------------

import { describeEtf } from "./etfDescription";
import type { Lang } from "./i18n";
import { profileFor } from "./lookthrough";
import type { ETFImplementation } from "./types";

export type EtfCommentInput = Pick<
  ETFImplementation,
  | "comment"
  | "commentDe"
  | "commentSource"
  | "exampleETF"
  | "isin"
  | "domicile"
  | "distribution"
  | "currency"
>;

export interface ResolvedEtfComment {
  /** The text to display / export. Empty string when neither a curated
   *  comment nor an auto-description is available. */
  text: string;
  /** Which branch the resolver took. The cell uses this to decide whether
   *  to apply italic styling for the runtime-only fallback. */
  source: "curated" | "auto" | "none";
}

export function resolveEtfImplementationComment(
  etf: EtfCommentInput,
  lang: Lang,
): ResolvedEtfComment {
  // Compute the live deterministic template up front (cheap; pure
  // function over the look-through profile). We only USE it when the
  // stored prose is auto-flagged or absent, but precomputing keeps the
  // branching tidy.
  const live = describeEtf({
    name: etf.exampleETF,
    profile: profileFor(etf.isin),
    catalog: {
      domicile: etf.domicile,
      distribution: etf.distribution,
      currency: etf.currency,
    },
  });

  // Stale-auto override: when the row's stored prose was generated by
  // describeEtf() and we have a fresh template result, the fresh result
  // wins — this lets a refreshed look-through profile light up the UI
  // immediately without waiting for the monthly backfill to re-stamp
  // the row. We still keep the stored text as a fallback when describe
  // yields null (look-through profile dropped, etc.).
  if (etf.commentSource === "auto") {
    if (live) {
      return { text: lang === "de" ? live.de : live.en, source: "auto" };
    }
    // No live profile — fall back to stored auto prose (still flagged
    // as auto so the cell keeps italic styling).
    if (lang === "de" && etf.commentDe && etf.commentDe.trim()) {
      return { text: etf.commentDe, source: "auto" };
    }
    if (etf.comment && etf.comment.trim()) {
      return { text: etf.comment, source: "auto" };
    }
    return { text: "", source: "none" };
  }

  if (lang === "de" && etf.commentDe && etf.commentDe.trim()) {
    return { text: etf.commentDe, source: "curated" };
  }
  if (etf.comment && etf.comment.trim()) {
    return { text: etf.comment, source: "curated" };
  }

  if (!live) return { text: "", source: "none" };
  return { text: lang === "de" ? live.de : live.en, source: "auto" };
}
