// Tests for the api-server's catalog-parser. Lives here (under
// investment-lab/tests) because vitest is already wired up here and the
// parser is dep-free, so cross-artifact import is harmless.
//
// Goal: lock in the field-extraction shape so a future edit of etfs.ts
// can't silently break the admin pane's replace-vs-add diff (a parser
// regression would manifest as "every key looks NEW", which is the worst
// kind of silent bug because the operator would happily open PRs that
// silently overwrite existing entries).

import { describe, it, expect } from "vitest";
import {
  findDuplicateIsinKey,
  findMatchingClose,
  parseCatalogFromSource,
} from "../../api-server/src/lib/catalog-parser";

const SAMPLE = `
import { foo } from "./bar";

const E = (x: ETFRecord) => x;

const CATALOG: Record<string, ETFRecord> = {
  // ---------- Equity ----------
  "Equity-Global": E({
    name: "SPDR MSCI ACWI IMI UCITS",
    isin: "IE00B3YLTY66",
    terBps: 17,
    domicile: "Ireland",
    replication: "Physical (sampled)",
    distribution: "Accumulating",
    currency: "USD",
    comment: "Single-fund global equity.",
    listings: { LSE: { ticker: "SPYI" }, XETRA: { ticker: "SPYI" } },
    defaultExchange: "LSE",
  }),
  "Equity-USA": E({
    name: "iShares Core S&P 500 UCITS",
    isin: "IE00B5BMR087",
    terBps: 7,
    domicile: "Ireland",
    replication: "Physical",
    distribution: "Accumulating",
    currency: "USD",
    comment: "Largest, most liquid S&P 500 UCITS.",
    listings: { LSE: { ticker: "CSPX" }, XETRA: { ticker: "SXR8" } },
    defaultExchange: "LSE",
    aumMillionsEUR: 80000,
    inceptionDate: "2010-05-19",
  }),
};
`;

describe("parseCatalogFromSource", () => {
  it("extracts every entry by key", () => {
    const out = parseCatalogFromSource(SAMPLE);
    expect(Object.keys(out).sort()).toEqual(["Equity-Global", "Equity-USA"]);
  });

  it("populates required string + number fields", () => {
    const out = parseCatalogFromSource(SAMPLE);
    const usa = out["Equity-USA"];
    expect(usa.key).toBe("Equity-USA");
    expect(usa.name).toBe("iShares Core S&P 500 UCITS");
    expect(usa.isin).toBe("IE00B5BMR087");
    expect(usa.terBps).toBe(7);
    expect(usa.domicile).toBe("Ireland");
    expect(usa.replication).toBe("Physical");
    expect(usa.distribution).toBe("Accumulating");
    expect(usa.currency).toBe("USD");
    expect(usa.comment).toBe("Largest, most liquid S&P 500 UCITS.");
    expect(usa.defaultExchange).toBe("LSE");
  });

  it("parses listings as a per-exchange ticker map", () => {
    const out = parseCatalogFromSource(SAMPLE);
    expect(out["Equity-Global"].listings).toEqual({
      LSE: { ticker: "SPYI" },
      XETRA: { ticker: "SPYI" },
    });
  });

  it("captures optional aumMillionsEUR / inceptionDate when present", () => {
    const out = parseCatalogFromSource(SAMPLE);
    expect(out["Equity-USA"].aumMillionsEUR).toBe(80000);
    expect(out["Equity-USA"].inceptionDate).toBe("2010-05-19");
  });

  it("leaves optional fields undefined when omitted", () => {
    const out = parseCatalogFromSource(SAMPLE);
    expect(out["Equity-Global"].aumMillionsEUR).toBeUndefined();
    expect(out["Equity-Global"].inceptionDate).toBeUndefined();
  });

  it("throws if the CATALOG marker is missing", () => {
    expect(() => parseCatalogFromSource("// nothing here\n")).toThrow(
      /Could not locate/,
    );
  });

  it("parses listings written with QUOTED keys (the renderer's output style)", () => {
    // renderEntryBlock emits `"LSE": { ticker: "..." }` via JSON.stringify.
    // The parser must accept that round-trip — otherwise REPLACE diffs of
    // PR-generated entries would always show "current listings: —".
    const src = `
      const CATALOG: Record<string, ETFRecord> = {
        "Equity-Bot": E({
          name: "Bot ETF",
          isin: "IE00BBBBBBB1",
          terBps: 8,
          domicile: "Ireland",
          replication: "Physical",
          distribution: "Accumulating",
          currency: "USD",
          comment: "Generated by the renderer.",
          listings: { "LSE": { ticker: "BOT" }, "XETRA": { ticker: "BTX" } },
          defaultExchange: "LSE",
        }),
      };
    `;
    const out = parseCatalogFromSource(src);
    expect(out["Equity-Bot"].listings).toEqual({
      LSE: { ticker: "BOT" },
      XETRA: { ticker: "BTX" },
    });
  });

  it("does not get confused by literal braces inside string fields", () => {
    // JSON.stringify does NOT escape `{` or `}`, so a future comment
    // containing braces must NOT corrupt brace-counting. Without
    // string-aware walking the parser would either truncate the entry
    // or skip the entry that follows.
    const src = `
      const CATALOG: Record<string, ETFRecord> = {
        "Equity-Tricky": E({
          name: "Tricky { Equity }",
          isin: "IE00TRICKY001",
          terBps: 9,
          domicile: "Ireland",
          replication: "Physical",
          distribution: "Accumulating",
          currency: "USD",
          comment: "Has } and { in it",
          listings: { LSE: { ticker: "TRK" } },
          defaultExchange: "LSE",
        }),
        "Equity-After": E({
          name: "After Tricky",
          isin: "IE00AFTER0001",
          terBps: 10,
          domicile: "Ireland",
          replication: "Physical",
          distribution: "Accumulating",
          currency: "USD",
          comment: "I should still parse.",
          listings: { LSE: { ticker: "AFT" } },
          defaultExchange: "LSE",
        }),
      };
    `;
    const out = parseCatalogFromSource(src);
    expect(Object.keys(out).sort()).toEqual(["Equity-After", "Equity-Tricky"]);
    expect(out["Equity-Tricky"].name).toBe("Tricky { Equity }");
    expect(out["Equity-After"].isin).toBe("IE00AFTER0001");
  });

  it("findMatchingClose treats string contents as opaque", () => {
    const src = '{ a: "} extra {", b: { c: 1 } }';
    const close = findMatchingClose(src, 0);
    expect(close).toBe(src.length - 1);
  });

  it("findMatchingClose skips line and block comments", () => {
    const src = "{ a: 1, // }\n /* } */ b: 2 }";
    const close = findMatchingClose(src, 0);
    expect(close).toBe(src.length - 1);
  });

  it('findMatchingClose handles "//" inside a string literal (URL case)', () => {
    // Belt-and-braces: strings are processed BEFORE the comment token,
    // so `https://...` inside a quoted value must not start a line
    // comment that would swallow the closing brace on the same line.
    const src = '{ url: "https://example.com/path//x" }';
    const close = findMatchingClose(src, 0);
    expect(close).toBe(src.length - 1);
  });

  describe("findDuplicateIsinKey", () => {
    const catalog = {
      "Equity-USA": {
        key: "Equity-USA",
        name: "S&P 500",
        isin: "IE00B5BMR087",
        terBps: 7,
        domicile: "Ireland",
        replication: "Physical",
        distribution: "Accumulating",
        currency: "USD",
        comment: "",
        listings: { LSE: { ticker: "CSPX" } },
        defaultExchange: "LSE",
      },
    };

    it("returns the conflicting key when ISIN is taken under a different key", () => {
      expect(findDuplicateIsinKey(catalog, "Equity-Other", "IE00B5BMR087")).toBe(
        "Equity-USA",
      );
    });

    it("returns null when the operator is editing the same-key entry", () => {
      expect(findDuplicateIsinKey(catalog, "Equity-USA", "IE00B5BMR087")).toBe(
        null,
      );
    });

    it("normalises case + whitespace on the input ISIN", () => {
      expect(findDuplicateIsinKey(catalog, "Equity-Other", " ie00b5bmr087 ")).toBe(
        "Equity-USA",
      );
    });

    it("returns null for an unseen ISIN", () => {
      expect(findDuplicateIsinKey(catalog, "Equity-New", "IE00BFRESH001")).toBe(
        null,
      );
    });
  });

  it("parses the real etfs.ts and finds well-known buckets", async () => {
    // Sanity check against the live source — if this fails, an etfs.ts
    // refactor has broken the parser shape and the admin pane's diff
    // will silently mis-classify entries.
    const { readFile } = await import("node:fs/promises");
    const path = await import("node:path");
    const real = await readFile(
      path.resolve(__dirname, "../src/lib/etfs.ts"),
      "utf8",
    );
    const out = parseCatalogFromSource(real);
    expect(out["Equity-Global"]).toBeDefined();
    expect(out["Equity-USA"]).toBeDefined();
    expect(out["Equity-USA"].isin).toBe("IE00B5BMR087");
    expect(out["Equity-USA"].terBps).toBeGreaterThan(0);
    expect(Object.keys(out["Equity-USA"].listings).length).toBeGreaterThan(0);
  });
});
