export default function Disclaimer2() {
  return (
    <div className="w-screen h-screen overflow-hidden relative bg-paper text-ink">
      <div className="absolute left-[7vw] top-[6vh] right-[7vw] flex items-baseline justify-between">
        <div className="font-mono uppercase tracking-[0.25em] text-[0.85vw] text-accent">
          08 · Methodology &amp; disclaimer — II of II
        </div>
        <div className="font-mono text-[0.85vw] text-ink/50">p. 12 · Sections 5–7</div>
      </div>

      <div className="absolute left-[7vw] right-[7vw] top-[12vh]">
        <h1 className="font-display font-medium text-[3.4vw] leading-none text-primary">
          Important information, continued.
        </h1>
        <div className="mt-[0.8vh] font-sans text-[1vw] text-ink/65 max-w-[60vw]">
          Data sources, suitability, and the report's standing.
        </div>
      </div>

      <div className="absolute left-[7vw] right-[7vw] top-[24vh] grid grid-cols-3 gap-x-[2.2vw]">
        <div>
          <div className="font-mono uppercase tracking-[0.2em] text-[0.78vw] text-accent">05 — Data sources</div>
          <div className="mt-[0.6vh] font-display text-[1.3vw] text-primary leading-tight">Third-party data carried at face value.</div>
          <div className="mt-[0.6vh] text-[0.9vw] leading-snug text-ink/85">
            ETF metadata, TERs, index compositions, and look-through holdings are sourced from public issuer documents and from justETF. Snapshots may be stale by up to a quarter. The Investment Decision Lab has not independently audited the underlying data and accepts no responsibility for third-party errors.
          </div>
        </div>
        <div>
          <div className="font-mono uppercase tracking-[0.2em] text-[0.78vw] text-accent">06 — Costs &amp; taxes</div>
          <div className="mt-[0.6vh] font-display text-[1.3vw] text-primary leading-tight">Personal frictions sit outside this report.</div>
          <div className="mt-[0.6vh] text-[0.9vw] leading-snug text-ink/85">
            Fee figures cover product TER, an indicative trading drag, and a typical Swiss retail custody fee. Withholding tax on foreign dividends, Swiss stamp duty, capital-gains treatment, and any pillar-3a or pension wrapper effects are excluded. Your actual after-tax outcome may differ materially.
          </div>
        </div>
        <div>
          <div className="font-mono uppercase tracking-[0.2em] text-[0.78vw] text-accent">07 — Suitability</div>
          <div className="mt-[0.6vh] font-display text-[1.3vw] text-primary leading-tight">Decisions remain with the investor.</div>
          <div className="mt-[0.6vh] text-[0.9vw] leading-snug text-ink/85">
            A 60/40 allocation can lose more than a quarter of its value in a single year. Before acting on anything in this document, satisfy yourself that you can bear the drawdown shown on the risk slide, that the ETFs are available and tax-efficient in your jurisdiction, and consider taking independent professional advice.
          </div>
        </div>
      </div>

      <div className="absolute left-[7vw] right-[7vw] bottom-[8vh] bg-primary text-paper p-[2.4vh_2.4vw] rounded-[0.4vw] flex items-center justify-between">
        <div className="max-w-[55vw]">
          <div className="font-mono uppercase tracking-[0.2em] text-[0.78vw] text-paper/60">Report identifier</div>
          <div className="mt-[0.6vh] font-display text-[1.8vw] leading-tight">ID-2026-0518-CHF-M60-15Y</div>
          <div className="mt-[0.6vh] text-[0.9vw] text-paper/70">
            Generated by the Investment Decision Lab on 18 May 2026. Snapshot of the engine and catalog as of that date — re-run for the current state.
          </div>
        </div>
        <div className="text-right">
          <div className="font-mono uppercase tracking-[0.2em] text-[0.78vw] text-paper/60">Prepared for</div>
          <div className="mt-[0.6vh] font-display text-[1.8vw] leading-tight text-accent">Example Investor</div>
          <div className="mt-[0.4vh] font-mono text-[0.9vw] text-paper/70">For illustration only</div>
        </div>
      </div>

      <div className="absolute left-0 right-0 bottom-0 h-[0.6vh] bg-accent/70" />
    </div>
  );
}
