function Section({
  heading,
  body,
}: {
  heading: string;
  body: React.ReactNode;
}) {
  return (
    <div className="mb-[1.4vh]">
      <span className="font-sans font-semibold text-primary text-[0.9vw]">
        {heading}
      </span>{" "}
      <span className="font-sans text-ink/85 text-[0.9vw] leading-[1.5]">{body}</span>
    </div>
  );
}

export default function Disclaimer3() {
  return (
    <div className="w-screen h-screen overflow-hidden relative bg-paper text-ink">
      <div className="absolute left-[7vw] top-[6vh] right-[7vw] flex items-baseline justify-between">
        <div className="font-mono uppercase tracking-[0.25em] text-[0.85vw] text-accent">
          Risk warning
        </div>
        <div className="font-mono text-[0.85vw] text-ink/50">p. 13 · Final notice</div>
      </div>

      <div className="absolute left-[7vw] right-[7vw] top-[11vh]">
        <h1 className="font-display font-medium text-[3vw] leading-none text-primary">
          Important Disclaimer &amp; Risk Warning
        </h1>
        <div className="mt-[0.8vh] font-sans italic text-[0.95vw] text-ink/60 max-w-[70vw]">
          Please read this disclaimer carefully before relying on any output of the Investment Decision Lab.
        </div>
      </div>

      <div className="absolute left-[7vw] right-[7vw] top-[22vh] bottom-[6vh] grid grid-cols-2 gap-x-[3vw] gap-y-[0.4vh]">
        <div>
          <Section
            heading="No Investment Advice."
            body="The information, allocations, ETF examples, rationales, scenarios, and any other content generated by this tool are provided strictly for general informational and educational purposes. They do not constitute investment advice, a personal recommendation, an offer or solicitation to buy or sell any financial instrument, nor a suitability or appropriateness assessment within the meaning of MiFID II, FIDLEG/FinSA, or any other applicable regulation."
          />
          <Section
            heading="Illustrative &amp; Deterministic Outputs."
            body="All allocations, fee estimates, stress-test impacts, and example ETFs are produced by a deterministic rule-based engine using simplified assumptions and illustrative parameters (e.g. assumed TERs, hypothetical historical-style shocks). They are not forecasts, not based on live market data, and should not be interpreted as projections of actual future performance."
          />
          <Section
            heading="Risk of Loss &amp; Past Performance."
            body="All investments involve risk, including the possible loss of the entire principal. Past performance and historical scenarios are not reliable indicators of future results. Equity, bond, commodity, real-estate, and digital-asset markets can experience severe and prolonged drawdowns. Currency movements can materially affect returns for non-base-currency exposures."
          />
          <Section
            heading="No Personalized Advice or Fiduciary Relationship."
            body="This tool does not know your full financial situation, objectives, liquidity needs, tax position, regulatory status, or capacity for loss. No fiduciary, advisory, or client relationship is created by your use of this tool. You remain solely responsible for any investment decision you make."
          />
        </div>
        <div>
          <Section
            heading="Tax &amp; Legal Considerations."
            body="Tax treatment depends on your individual circumstances and jurisdiction and may change. Certain instruments (including UCITS ETFs, US-domiciled ETFs, crypto assets, and derivatives) may not be available, suitable, or legally distributable to all investors. Always consult a qualified tax and legal adviser before acting."
          />
          <Section
            heading="Third-Party Instruments."
            body="Any ETF tickers, issuers, or product names shown are examples only and are not endorsements. We do not guarantee the accuracy, completeness, or current availability of any instrument. Always read the relevant Key Information Document (KID/KIID), prospectus, and factsheet before investing."
          />
          <Section
            heading="Seek Professional Advice."
            body="Before making any investment decision, you should obtain independent financial, tax, and legal advice from a duly licensed professional who can take your personal circumstances into account. By using this tool you acknowledge and accept the limitations described above and agree that the operators and authors disclaim, to the fullest extent permitted by law, any liability for losses arising from reliance on its output."
          />

          <div className="mt-[1.6vh] border border-accent/40 bg-accent/10 rounded-[0.3vw] p-[1vh_1vw]">
            <div className="font-mono uppercase tracking-[0.2em] text-[0.7vw] text-accent">
              A BICon showcase
            </div>
            <div className="mt-[0.4vh] font-sans text-[0.85vw] text-ink/80">
              The Investment Decision Lab is presented as a BICon showcase. Use of the tool implies acceptance of this disclaimer in full.
            </div>
          </div>
        </div>
      </div>

      <div className="absolute left-0 right-0 bottom-0 h-[0.6vh] bg-accent/70" />
    </div>
  );
}
